/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * UserResponse
         * @description 用户响应
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Username */
            username: string;
            /**
             * Avatar Url
             * @default null
             */
            avatar_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DocumentResponse
         * @description 文档响应
         */
        DocumentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /**
             * Source Url
             * @default null
             */
            source_url: string | null;
            /** Status */
            status: string;
            /** Tags */
            tags: string[];
            /** Chunk Count */
            chunk_count: number;
            /**
             * Error Message
             * @default null
             */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Processed At
             * @default null
             */
            processed_at: string | null;
        };
        /**
         * DuplicateDetected
         * @description 重复文档检测
         */
        DuplicateDetected: {
            /** Source Id */
            source_id: string;
            /**
             * Existing Doc Id
             * Format: uuid
             */
            existing_doc_id: string;
            /** Existing Title */
            existing_title: string;
            /** Message */
            message: string;
        };
        /**
         * QuizQuestion
         * @description 测验题目
         */
        QuizQuestion: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Question */
            question: string;
            /**
             * Options
             * @default null
             */
            options: {
                [key: string]: unknown;
            } | null;
            /** Topic */
            topic: string;
        };
        /**
         * SuggestedReview
         * @description 加入复习计划建议项
         */
        SuggestedReview: {
            /**
             * Wrong Id
             * Format: uuid
             */
            wrong_id: string;
            /** Question */
            question: {
                [key: string]: unknown;
            };
            /**
             * User Answer
             * @default null
             */
            user_answer: string | null;
            /**
             * Correct Answer
             * @default null
             */
            correct_answer: string | null;
            /**
             * Explanation
             * @default null
             */
            explanation: string | null;
        };
        /**
         * ReviewItem
         * @description 复习项目
         */
        ReviewItem: {
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            /**
             * Chunk Id
             * @default null
             */
            chunk_id: string | null;
            /** Topic */
            topic: string;
            /**
             * Answer
             * @default null
             */
            answer: string | null;
            /** Mastery Score */
            mastery_score: number;
            /**
             * Next Review
             * Format: date-time
             */
            next_review: string;
            /** Interval Days */
            interval_days: number;
            /** Review Count */
            review_count: number;
            /** Status */
            status: string;
            /**
             * Source
             * @default null
             */
            source: string | null;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /**
             * Is Mastered
             * @default false
             */
            is_mastered: boolean;
            /**
             * Correct Streak
             * @default 0
             */
            correct_streak: number;
        };
        /**
         * NormalReviewAnswer
         * @description 正式复习作答选项（前端3级映射后端5级）
         * @enum {string}
         */
        NormalReviewAnswer: "mastered" | "vague" | "forgotten";
        /** SearchResult */
        SearchResult: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Content */
            content: string;
            /** Score */
            score: number;
            /**
             * Topic
             * @default null
             */
            topic: string | null;
            /**
             * Metadata
             * @default null
             */
            metadata: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * UserCreate
         * @description 创建用户请求
         */
        UserCreate: {
            /** Email */
            email: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * UserLogin
         * @description 用户登录请求
         */
        UserLogin: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Token
         * @description JWT Token 响应
         */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserResponse"];
        };
        /**
         * DocumentCreate
         * @description 创建文档请求
         */
        DocumentCreate: {
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /**
             * Source Url
             * @default null
             */
            source_url: string | null;
            /**
             * File Path
             * @default null
             */
            file_path: string | null;
            /**
             * Content
             * @default null
             */
            content: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /**
         * DocumentImport
         * @description 批量导入请求
         */
        DocumentImport: {
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * On Duplicate
             * @default ask
             */
            on_duplicate: string;
        };
        /**
         * ImportResult
         * @description 导入结果
         */
        ImportResult: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Skipped */
            skipped: number;
            /** Documents */
            documents: components["schemas"]["DocumentResponse"][];
            /**
             * Duplicates
             * @default []
             */
            duplicates: components["schemas"]["DuplicateDetected"][];
        };
        /**
         * ThreadCreate
         * @description 创建 Thread 请求
         */
        ThreadCreate: {
            /** Agent Type */
            agent_type: string;
        };
        /**
         * ThreadResponse
         * @description Thread 响应
         */
        ThreadResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Agent Type */
            agent_type: string;
            /**
             * Title
             * @default null
             */
            title: string | null;
            /** Status */
            status: string;
            /** State */
            state: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RunCreate
         * @description 创建 Run 请求
         */
        RunCreate: {
            /** Agent Type */
            agent_type: string;
            /** Action */
            action: string;
            /**
             * Input
             * @default {}
             */
            input: {
                [key: string]: unknown;
            } | string;
        };
        /**
         * RunResponse
         * @description Run 响应
         */
        RunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Agent Type */
            agent_type: string;
            /** Status */
            status: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /**
             * Output
             * @default null
             */
            output: {
                [key: string]: unknown;
            } | null;
            /**
             * Hitl Required
             * @default false
             */
            hitl_required: boolean;
            /**
             * Hitl Action
             * @default null
             */
            hitl_action: string | null;
            /**
             * Hitl Options
             * @default null
             */
            hitl_options: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
        };
        /**
         * HITLResume
         * @description HITL 恢复请求
         */
        HITLResume: {
            /** Action */
            action: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
        };
        /**
         * SSEEvent
         * @description SSE 事件
         */
        SSEEvent: {
            /** Event */
            event: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Run Id
             * @default null
             */
            run_id: string | null;
            /**
             * Timestamp
             * Format: date-time
             * @default 2026-09-11T05:50:52.755985
             */
            timestamp: string;
        };
        /**
         * QuizGenerate
         * @description 生成测验请求
         */
        QuizGenerate: {
            /** Scope */
            scope: string;
            /**
             * Topic
             * @default null
             */
            topic: string | null;
            /**
             * Time Range
             * @default null
             */
            time_range: {
                [key: string]: unknown;
            } | null;
            /**
             * Question Count
             * @default 5
             */
            question_count: number;
            /**
             * Difficulty
             * @default medium
             */
            difficulty: string;
        };
        /**
         * QuizResponse
         * @description 测验响应
         */
        QuizResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scope */
            scope: string;
            /**
             * Topic
             * @default null
             */
            topic: string | null;
            /** Questions */
            questions: components["schemas"]["QuizQuestion"][];
            /** Total Questions */
            total_questions: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * QuizSubmit
         * @description 提交测验答案
         */
        QuizSubmit: {
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /** Answers */
            answers: {
                [key: string]: unknown;
            };
        };
        /**
         * QuizResult
         * @description 测验结果
         */
        QuizResult: {
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /** Score */
            score: number;
            /** Total Questions */
            total_questions: number;
            /** Correct Count */
            correct_count: number;
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
            /** Wrong Questions */
            wrong_questions: {
                [key: string]: unknown;
            }[];
            /**
             * Suggested Reviews
             * @default []
             */
            suggested_reviews: components["schemas"]["SuggestedReview"][];
            /** Mastery Change */
            mastery_change: number;
            /** Time Spent Seconds */
            time_spent_seconds: number;
        };
        /**
         * WrongQuestionResponse
         * @description 错题响应
         */
        WrongQuestionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Question */
            question: {
                [key: string]: unknown;
            };
            /**
             * User Answer
             * @default null
             */
            user_answer: string | null;
            /**
             * Correct Answer
             * @default null
             */
            correct_answer: string | null;
            /**
             * Explanation
             * @default null
             */
            explanation: string | null;
            /** Review Count */
            review_count: number;
            /** Mastered */
            mastered: boolean;
            /**
             * In Review
             * @default false
             */
            in_review: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AddToReviewRequest
         * @description 将错题加入复习计划
         */
        AddToReviewRequest: {
            /** Wrong Ids */
            wrong_ids: string[];
        };
        /**
         * AddToReviewResponse
         * @description 加入复习计划结果
         */
        AddToReviewResponse: {
            /** Added */
            added: number;
            /** Skipped */
            skipped: number;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ReviewSubmit
         * @description 提交复习结果（兼容旧版本）
         */
        ReviewSubmit: {
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            /** Result */
            result: string;
        };
        /**
         * ReviewResult
         * @description 复习结果
         */
        ReviewResult: {
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            /** Old Interval */
            old_interval: number;
            /** New Interval */
            new_interval: number;
            /** Ease Factor */
            ease_factor: number;
            /** Mastery Score */
            mastery_score: number;
            /**
             * Next Review
             * Format: date-time
             */
            next_review: string;
            /** Status */
            status: string;
        };
        /**
         * ReviewListResponse
         * @description 复习清单响应
         */
        ReviewListResponse: {
            /** Pending Count */
            pending_count: number;
            /** Overdue Count */
            overdue_count: number;
            /** Items */
            items: components["schemas"]["ReviewItem"][];
        };
        /**
         * NormalReviewSubmit
         * @description 正式复习提交（前端3级映射）
         */
        NormalReviewSubmit: {
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            answer: components["schemas"]["NormalReviewAnswer"];
            /**
             * Response Time Ms
             * @default 0
             */
            response_time_ms: number;
        };
        /**
         * NormalReviewResponse
         * @description 正式复习响应
         */
        NormalReviewResponse: {
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            /**
             * Chunk Id
             * @default null
             */
            chunk_id: string | null;
            /**
             * Next Review Time
             * Format: date-time
             */
            next_review_time: string;
            /** Ease Factor */
            ease_factor: number;
            /** Correct Streak */
            correct_streak: number;
            /** Is Mastered */
            is_mastered: boolean;
            /**
             * Need Session Retry
             * @default false
             */
            need_session_retry: boolean;
            /**
             * Retry Reason
             * @default null
             */
            retry_reason: string | null;
            /**
             * Mastery Change
             * @default null
             */
            mastery_change: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SessionRetrySubmit
         * @description 会话重试提交（仅用于日志记录，可选）
         */
        SessionRetrySubmit: {
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            answer: components["schemas"]["NormalReviewAnswer"];
            /**
             * Response Time Ms
             * @default 0
             */
            response_time_ms: number;
        };
        /**
         * VerificationSubmit
         * @description 验证提交
         */
        VerificationSubmit: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Schedule Id
             * @default null
             */
            schedule_id: string | null;
            /** Verification Type */
            verification_type: string;
            /** User Answer */
            user_answer: string;
        };
        /**
         * VerificationFailedSubmit
         * @description 组后验证失败提交（轻降难度，不重置间隔）
         */
        VerificationFailedSubmit: {
            /**
             * Chunk Id
             * @default null
             */
            chunk_id: string | null;
            /**
             * Schedule Id
             * @default null
             */
            schedule_id: string | null;
            /**
             * Response Time Ms
             * @default 0
             */
            response_time_ms: number;
        };
        /**
         * VerificationResponse
         * @description 验证响应
         */
        VerificationResponse: {
            /** Passed */
            passed: boolean;
            /**
             * Ai Score
             * @default null
             */
            ai_score: number | null;
            /**
             * Feedback
             * @default null
             */
            feedback: string | null;
            /**
             * Need Retry
             * @default false
             */
            need_retry: boolean;
        };
        /**
         * FeynmanVerifySubmit
         * @description 组后验证费曼评分提交
         */
        FeynmanVerifySubmit: {
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            /** Explanation */
            explanation: string;
        };
        /**
         * FeynmanVerifyResponse
         * @description 组后验证费曼评分响应
         */
        FeynmanVerifyResponse: {
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /**
             * Strengths
             * @default []
             */
            strengths: string[];
            /**
             * Weaknesses
             * @default []
             */
            weaknesses: string[];
            /**
             * Suggestions
             * @default []
             */
            suggestions: string[];
            /**
             * Correct Answer
             * @default
             */
            correct_answer: string;
        };
        /**
         * SessionSnapshot
         * @description 复习会话快照（前端内存结构原样存储，不做后端校验）
         */
        SessionSnapshot: {
            /** Batch Id */
            batch_id: string;
            /** Batch Index */
            batch_index: number;
            /** Main Queue */
            main_queue: components["schemas"]["ReviewItem"][];
            /**
             * Retry Queue
             * @default []
             */
            retry_queue: {
                [key: string]: unknown;
            }[];
            /**
             * Verify Queue
             * @default []
             */
            verify_queue: {
                [key: string]: unknown;
            }[];
            /** @default null */
            current_card: components["schemas"]["ReviewItem"] | null;
            /**
             * Stats
             * @default {}
             */
            stats: {
                [key: string]: unknown;
            };
        };
        /**
         * BatchCompleteSubmit
         * @description 复习组完成埋点上报
         */
        BatchCompleteSubmit: {
            /** Batch Id */
            batch_id: string;
            /** Total Count */
            total_count: number;
            /** Mastered Count */
            mastered_count: number;
            /** Retry Count */
            retry_count: number;
            /** Duration Sec */
            duration_sec: number;
            /** Avg Response Ms */
            avg_response_ms: number;
        };
        /**
         * FeynmanStart
         * @description 开始费曼会话请求
         */
        FeynmanStart: {
            /** Topic */
            topic: string;
            /**
             * Knowledge Context
             * @default null
             */
            knowledge_context: string | null;
        };
        /**
         * FeynmanExplain
         * @description 提交费曼解释
         */
        FeynmanExplain: {
            /** Explanation */
            explanation: string;
        };
        /**
         * FeynmanResponse
         * @description 费曼会话响应
         */
        FeynmanResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Topic */
            topic: string;
            /** State */
            state: string;
            /** Rounds */
            rounds: number;
            /**
             * Score
             * @default null
             */
            score: number | null;
            /**
             * Evaluation
             * @default null
             */
            evaluation: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FeynmanEvaluate
         * @description 费曼评估结果
         */
        FeynmanEvaluate: {
            /** Score */
            score: number;
            /**
             * Strengths
             * @default []
             */
            strengths: string[];
            /**
             * Weaknesses
             * @default []
             */
            weaknesses: string[];
            /**
             * Suggestions
             * @default []
             */
            suggestions: string[];
            /**
             * Keywords Covered
             * @default []
             */
            keywords_covered: string[];
            /**
             * Keywords Missing
             * @default []
             */
            keywords_missing: string[];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResult"][];
            /**
             * Rewritten Query
             * @default null
             */
            rewritten_query: string | null;
            /** Total Results */
            total_results: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
